# Generated by Django 5.0.3 on 2024-03-23 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="home",
            name="enroll_id",
            field=models.IntegerField(default=0),
        ),
    ]
